version: "3.8"

services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
